import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "@/ThemeRegistry/ThemeRegistry";
import { roboto } from "@/ThemeRegistry/font";
import Paper from "@mui/material/Paper";
import BottomBarNavigation from "@/components/BottomBarNavigation";
import ErrorContainer from "@/components/ErrorContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <Paper
          component="body"
          elevation={8}
          className={`${roboto.className} min-h-screen`}
        >
          <ErrorContainer>{children}</ErrorContainer>
          <BottomBarNavigation />
        </Paper>
      </ThemeRegistry>
    </html>
  );
}
