import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "@/ThemeRegistry/ThemeRegistry";
import { poppins } from "@/ThemeRegistry/font";
import Paper from "@mui/material/Paper";
import BottomBarNavigation from "@/components/BottomBarNavigation";
import ErrorContainer from "@/components/ErrorContainer";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  picturePreviewModal,
}: {
  children: React.ReactNode;
  picturePreviewModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <Paper
          component="body"
          elevation={8}
          className={`${poppins.className} min-h-screen`}
        >
          <Box className="max-w-3xl mx-auto">
            <ErrorContainer>{children}</ErrorContainer>
            <BottomBarNavigation />
          </Box>
        </Paper>
        {picturePreviewModal}
      </ThemeRegistry>
    </html>
  );
}
